osx_image: xcode7.3
language: objective-c
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script: set -o pipefail && xcodebuild test -workspace Example/RxErrorTracker.xcworkspace -scheme RxErrorTracker-Example -sdk iphonesimulator9.3 | xcpretty